config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => 'sessions#new'
  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :restaurants do
    resources :reviews, :except => [:edit, :update, :destroy]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_attached_file :restaurant_photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :restaurant_photo, :content_type => /\Aimage\/.*\Z/
  validates :restaurant_photo, :attachment_presence => true
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email

  validates :email, presence: true,
                  uniqueness: { case_sensitive: false },
                  format: {
                    with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]+\Z/
                  }

  has_many :reviews

  before_save :downcase_userinfo

  has_attached_file :user_photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :user_photo, :content_type => /\Aimage\/.*\Z/
  validates :user_photo, :attachment_presence => true

  private
    def downcase_userinfo
      self.email = self.email.downcase if self.email
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurnt_params)
    if @restaurant.update
      redirect_to restaurant_path(@restaurant)
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.delete
  end

  private
    def restaurant_params
       params.require(:restaurant).permit(:restaurant_photo, :name, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authorize, only: [:edit, :update]

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def new
    restaurant = Restaurant.find(params[:restaurant_id])
    @review = restaurant.reviews.new
  end

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    @review = restaurant.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to restaurant_path(restaurant)
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
    @review = @reviews.find(params[:id])
  end

private
  def review_params
    params.require(:review).permit(:review_details, :rating, :user_id, :restaurant_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_photo, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <nav id="nav" class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <ul class="nav nav-pills">
        <ul class="nav navbar-nav pull-left">
          <li><%= image_tag("yelp.png", height: '60', width: '60', :id => "nav_logo") %></li>
          <% if current_user %>
            <li><span id="user_nav_label"><%= current_user.email %></span></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if current_user %>
            <li><%= link_to "My Reviews", user_path(current_user) %></li>
            <li><%= link_to "Browse Restaurants", restaurants_path %></li>
            <li><%= link_to "Log Out", logout_path %></li>
            <li class="active"><%= link_to "Home", root_url %></li>
          <% end %>
          <div id="current_user_login">
  <% if !current_user %>
    <%= link_to "Sign Up", signup_path, class: "btn btn-warning btn-lg" %> or
    <%= link_to "Log In", login_path, class: "btn btn-success btn-lg" %>
  <% end %>
</div>
        </ul>
      </ul>
    </div>
  </nav>
</head>
<body>





<%= yield %>


</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :url => restaurants_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  <div class="form-group">
    <%= f.file_field :restaurant_photo %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/restaurants/index.html.erb
<h1> Restaurants </h1>
<br />

<% @restaurants.each do |restaurant| %>
  <p><%= image_tag restaurant.restaurant_photo.url(:thumb) %><p>
  <p><%= link_to restaurant.name, restaurant_path(restaurant), class: "btn btn-default" %></p>
  <p><%= link_to "#{restaurant.reviews.count} reviews", restaurant_reviews_path(restaurant), class: "btn btn-default" %></p>
  <br />
  <br />
<% end %>

<%= link_to "Add A Restaurant", new_restaurant_path, class: "btn btn-warning" %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %> </h1>
<h4> <%= @restaurant.reviews.count %> reviews <h4>
<h3> <%= @restaurant.description %> </h3>
<p><%= image_tag @restaurant.restaurant_photo.url(:medium), :id => "restaurant_show_image" %><p>

<% @restaurant.reviews.each do |review| %>
  <p><%= link_to "review details", restaurant_review_path(@restaurant, review), class: "btn btn-default" %></p>
  <p><%= image_tag User.find(review.user_id).user_photo.url(:thumb) %></p>
  <p><%= review.review_details %></p>
<% end %>

<%= link_to "Add A Review", new_restaurant_review_path(@restaurant), class: "btn btn-danger" %>

app/views/reviews/_form.html.erb
<%= form_for @review, :url => restaurant_reviews_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :review_details %>
    <%= f.text_field :review_details %>
  </div>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.select(:rating, options_for_select([['★', 1], ['★★', 2], ['★★★', 3], ['★★★★', 4], ['★★★★★', 5]])) %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/reviews/index.html.erb
<h1> Reviews </h1>



<% @reviews.each do |review| %>
  <p>Description: <%= review.review_details %></p>
  <p>Rating: <%= review.rating %></p>
  <br />
  <br />
<% end %>

<%= link_to "Add A Review", new_restaurant_review_path(@restaurant), class: "btn btn-warning" %>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/reviews/show.html.erb
<p><%= image_tag User.find(@review.user_id).user_photo.url(:thumb) %></p>
<h1> <%= @review.rating %> </h1>
<h3> <%= @review.review_details %> </h3>

app/views/users/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<video autoplay loop poster="/assets/restaurant2.jpg" id="bgvid">
  <source src="/assets/bgvideo.webm" type="video/webm" />
  <source src="/assets/bgvideo.mp4" type="video/mp4" />
</video>

<div id= "new_session_wrapper">
<h1>Sign Up</h1>



<%= form_for @user, :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field btn btn-lg">
    <%= f.file_field :user_photo %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>
</div>

app/views/users/show.html.erb
<div id="user_show_wrapper">
  <div id="welcome">
    <h1> Welcome <%= @user.email %> </h1>
  </div>

<%= image_tag @user.user_photo.url(:thumb), id: "user_avatar" %>
<br />
<h2> Your Reviews: </h2>

<% @user.reviews.each do |review| %>
  <%= review.review_details %>
<% end %>

<%= link_to "view restaurants", restaurants_path %>
</div>